// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedCents.Data;

#nullable disable

namespace SharedCents.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514201303_SeedExpenses")]
    partial class SeedExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SharedCents.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpenseId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpenseId = 1,
                            Amount = 1000m,
                            Category = "Housing",
                            DueDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Rent",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 2,
                            Amount = 145m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Electric Bill",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 3,
                            Amount = 72m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Water Bill",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 4,
                            Amount = 85m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Internet",
                            IsPaid = true,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 5,
                            Amount = 210m,
                            Category = "Food",
                            DueDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Groceries",
                            IsPaid = true,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 6,
                            Amount = 168m,
                            Category = "Transportation",
                            DueDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Car Insurance",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 7,
                            Amount = 95m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Phone Bill",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 8,
                            Amount = 48m,
                            Category = "Entertainment",
                            DueDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Streaming Services",
                            IsPaid = true,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 9,
                            Amount = 120m,
                            Category = "Transportation",
                            DueDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Gas",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 10,
                            Amount = 90m,
                            Category = "Food",
                            DueDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Dining Out",
                            IsPaid = true,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 11,
                            Amount = 1000m,
                            Category = "Housing",
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Rent",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 12,
                            Amount = 138m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Electric Bill",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 13,
                            Amount = 69m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Water Bill",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 14,
                            Amount = 85m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Internet",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 15,
                            Amount = 235m,
                            Category = "Food",
                            DueDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Groceries",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 16,
                            Amount = 420m,
                            Category = "Transportation",
                            DueDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Car Payment",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 17,
                            Amount = 168m,
                            Category = "Transportation",
                            DueDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Car Insurance",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 18,
                            Amount = 95m,
                            Category = "Utilities",
                            DueDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Phone Bill",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 19,
                            Amount = 76m,
                            Category = "Household",
                            DueDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Household Supplies",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 20,
                            Amount = 48m,
                            Category = "Entertainment",
                            DueDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Streaming Services",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 21,
                            Amount = 115m,
                            Category = "Transportation",
                            DueDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Gas",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 22,
                            Amount = 105m,
                            Category = "Food",
                            DueDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Dining Out",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 23,
                            Amount = 64m,
                            Category = "Pets",
                            DueDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Pet Supplies",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        },
                        new
                        {
                            ExpenseId = 24,
                            Amount = 40m,
                            Category = "Health",
                            DueDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Medical Copay",
                            IsPaid = false,
                            IsShared = false,
                            PartnerId = 1
                        },
                        new
                        {
                            ExpenseId = 25,
                            Amount = 250m,
                            Category = "Savings",
                            DueDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseName = "Savings Transfer",
                            IsPaid = false,
                            IsShared = true,
                            PartnerId = 2
                        });
                });

            modelBuilder.Entity("SharedCents.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            PartnerId = 1,
                            Email = "jasmine@email.com",
                            FirstName = "Jasmine",
                            MonthlyIncome = 3200m
                        },
                        new
                        {
                            PartnerId = 2,
                            Email = "Adrian@email.com",
                            FirstName = "Adrian",
                            MonthlyIncome = 3500m
                        });
                });

            modelBuilder.Entity("SharedCents.Models.Expense", b =>
                {
                    b.HasOne("SharedCents.Models.Partner", "Partner")
                        .WithMany("Expenses")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("SharedCents.Models.Partner", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
